### ISSUE TITLE
Redo Bingham analysis at the end of the New_Data notebook

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/2015_Umkondo#12]
Once the tilt-corrections are updated and the new legacy data are added these Bingham analysis needs to be redone as noted in Umkondo_MS_comments.rtf

**Comment by tmkilian** [comment]
Hopefully I won't have to do this again...

**Comment by Swanson-Hysell** [comment]
One last time...let's just do the vertical since that the one that actually shows the information. The file name has changed so that is is now: 'Umk_data_rot.txt'. For some reason, my pmagpy installation isn't making the plot.

The ideal situation would be to make it so the eqarea_ell can be run natively in the notebook. We should do this at some point so that we can plot other confidence ellipses in addition to Fisher in the notebook. That way we wouldn't have to do outside of the notebook command line work when there are changes. But for now what will hopefully be the last eqarea_ell run.

**Comment by tmkilian** [comment]
updated the Bingham plot for means rotated into to vertical. Erased unrotated Bingham plot because it is pretty redundant.
