### ISSUE TITLE
Add notes to manuscript table related to pmag abbreviations

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/2015_Umkondo#2]

**Comment by tmkilian** [comment]
Added abbreviations. If we add in situ dec/inc then this will need to be adjusted in the table.

**Comment by tmkilian** [comment]
Added "Dec", "Inc", "Dec_tc", and "Inc_tc" to definitions in the table caption. They should be labeled accordingly when the new latex table is inserted into the MS.
