### ISSUE TITLE
Update table to have both insitu and tilt-corrected values

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/2015_Umkondo#3]
Recall that table output is from a pandas data frame in the notebook which should be changed to have both insitu and tilt-corrected columns.

**Comment by tmkilian** [comment]
This is going to take quite a bit of time and expand the supplement by a lot. If you remember, before we touched the data in the notebooks we sorted out just the tilt-corrected specimen results. This would mean that we need to go back through and create new tables and means for all of the in situ directions. I think that we would need to do this for all of the Seidel/Pancake data and for all of the new data. One way of possibly getting around this is to create a copy of the notebooks and change the just the filter from tilt-corrected (100) to in situ (0) - without changing any of the labels. This would allow us to use the copy of the notebook just to create a table with in situ dec and inc.

**Comment by Swanson-Hysell** [comment]
Since we applied uniform tilt-corrections to all samples in a given site shouldn't we simply be able to apply the reverse of the given tilt-correction to rotate a tilt-corrected site mean back to insitu coordinates? a95 and kappa should stay the same. 



Nick

**Comment by tmkilian** [comment]
Gotcha. Pretty straightforward.

Some of the data from older studies and the Gose+06 paper don't document their tilt corrections but mention in the text that they are used when sediments are available to measure....I documented this for all of the sites in the final table.

There are also a couple of intrusion means were tilt corrections were used for PW- sites but not for Pancake data (or they are different). I documented when this was the case and we can decide what to do with it later.

**Comment by tmkilian** [comment]
Inserted uncorrected dec/inc for sites that we have the data. Some of the older papers don't document the full range of tilt corrections and only show tilt corrected means...I inserted ND into the column when this was the case. We can add a superscript reference to the table caption to describe the absence of values.

**Comment by tmkilian** [comment]
Ok. Finished adding all uncorr dec/inc data. When the site was not tilt-corrected, then NaN is used. When we are unsure of whether or not a tilt-correction was used (not documented numerically in studies), then ND is used instead of NaN.
