### ISSUE TITLE
Make grand mean table

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/2015_Umkondo#4]
Put in the fields that Reviewer 1 wants to have.

**Comment by tmkilian** [comment]
Made table 2 in the New data notebook.Didn't add everything that Pesonen desired. Figuring our sample and specimen numbers might be a pain in the ass, just going through and counting everything. It will also be difficult to add the B/N/n into the pandas data frame, right? Will we have to do this manually in the .tex?

**Comment by tmkilian** [comment]
I can use the er_sample file (for each data set) to easily count total sample numbers.

**Comment by tmkilian** [comment]
made table of total samples measured, don't know what to do with it yet

**Comment by tmkilian** [comment]
finished mean table...with latex output, at end of New_Data notebook - could add total sample numbers to cooling unit numbers using 'Umkondo_Site_Mean_with_n-N.csv' located in /2015_Umkondo/Data.

**Comment by Swanson-Hysell** [comment]
I'm still working on finishing the formatting and notes on this table, but it is effectively in there at this point.
