### ISSUE TITLE
Have a look at Wilson et al. 1987 and Mare et al. 2006 data

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/2015_Umkondo#5]
Means can be found through a Paleomagia search: http://h175.it.helsinki.fi/database/form1.php

**Comment by tmkilian** [comment]
Having a really hard time getting the Wilson et al. (1987) paper. It is in the Mafic Dyke Swarms book eds. Halls and Fahrig. Any chance you have that? It is not at UCB but there are copies at Davis and Santa Cruz...

I was able to get the data from Paleomagia. However, they are combined means and in the case of Mare et al. (2006) I only used two VGPs from the paper, not the mean given by Paleomagia. There was overlap with sites from Seidel (2004).

Might be tough to evaluate the data from Wilson et al. (1987) without being able to look at the paper. I am trying to get a copy.

**Comment by tmkilian** [comment]
Added Mare et al. (2006) data to notebook

**Comment by Swanson-Hysell** [comment]
Hey Taylor,




Quick glimpse of internet between Lake Superior Islands. I don’t have the Wilson paper. I bet the interlibrary loan from Davis or Santa Cruz is quite quick however. I think they run a daily shuttle to Davis.




Look forward to checking in about the manuscript/notebook revisions soon!




Nick

**Comment by tmkilian** [comment]
Ran into this during library loan request:

![screen_shot](https://cloud.githubusercontent.com/assets/6721022/8817197/3a8dd048-2fe5-11e5-993d-f73cfe72b8c3.png)

**Comment by Swanson-Hysell** [comment]
If you call up the Earth Science library (or visit them on the ground floor of McCone), they will be able to help you get it. 



Nick

**Comment by tmkilian** [comment]
Ok. Got the special issue.

Re: Wilson et al. (1987) - there is one possible Umkondo-aged dike located in NE Zimbabwe along a major fault system. The exact location is referenced with some strange grid number and there are only 5 samples in the site (demonetization circles used for two of the samples). The plot of the direction suggests that it is NNE Umkondo, however the mean direction quoted in the text (N=5, D=181.4, I=-15.4, k=95.3, a95=7.9) is clearly a South-seeking direction. They must have reversed the direction for the figure!

Anyways, do we want to add this?

There is also another intrusion in Northern zimbabwe (among the Deweras dikes) that intrudes Deweras group lavas. It yields a North-seeking Umkondo like direction. This could be added to the compilation as well (N=7 (two from a baked contact next to the dike), D=10.6, I=9.3, k=27.8, a95=11.6). 

With both these intrusions, there is considerable age uncertainty and the exact sampling localities are unknown...
