### ISSUE TITLE
Add WRD6 and 7 from Mare to the compilation

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/2015_Umkondo#7]
These sites have poor stats, but will be filtered out when we calculate a mean.

**Comment by tmkilian** [comment]
There is a problem when calculating the dispersion using IPmag.sb_vgp_calc, which needs the k values. These are not given for both Mare et al. (2006) and Wilson et al. (1987) sites...

**Comment by Swanson-Hysell** [comment]
Let's filter out entries without kappa values before calculating scatter. And it would be better to filter based on presence of kappa rather than doing a manual drop.

**Comment by tmkilian** [comment]
Put filter on DF used for calculating Sb. Now only sites with k values will be used.
