### ISSUE TITLE
Figure 1 changes

### ISSUE THREAD

**Issue by tmkilian** [Swanson-Hysell-Group/2015_Umkondo#8]
within WG there are some gray polygons that need to be turned blue

**Comment by tmkilian** [comment]
Change heading "1.88-1.1..." to "1.93–1.1 Ga..."

Change "basalt lavas in Soutpansberg Group" to "lavas and dolerites in Soutpansberg Group"

Change colors things in SG region to all be the same - instead of green make all intrusions another (lighter) shade of gray

Delete Mazowe dikes from figure and key.

Change "diabases" to "dolerites"

**Comment by Swanson-Hysell** [comment]
Unless we hear otherwise from Richard, I think we can consider this issue closed.
